# Generated by Django 3.1.7 on 2025-07-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mileage', models.CharField(blank=True, max_length=20)),
                ('rent_per_day', models.PositiveIntegerField()),
            ],
        ),
    ]
