# Generated by Django 3.1.7 on 2025-08-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='deposit_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
