# Generated by Django 3.1.7 on 2025-08-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='deposit_amount',
        ),
    ]
