# Generated by Django 3.1.7 on 2025-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_bikemodel_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
