# Generated by Django 5.2.5 on 2025-08-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_bikemodel_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
