# Generated by Django 3.1.7 on 2025-10-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_bikemodel_deposit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_image', models.FileField(blank=True, null=True, upload_to='offers_dir/')),
                ('description', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
