# Generated by Django 3.1.7 on 2025-10-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
