# Generated by Django 3.1.7 on 2025-11-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20251030_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
