# Generated by Django 3.1.7 on 2025-11-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20251120_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='Vehicle_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
