# Generated by Django 3.1.7 on 2025-11-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_bikemodel_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='Onwer_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
