# Generated by Django 3.1.7 on 2025-11-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_bikemodel_onwer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='Status',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
