# Generated by Django 3.1.7 on 2025-12-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_bikemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='bike_image',
            field=models.FileField(blank=True, null=True, upload_to='bike_pics/'),
        ),
    ]
