# Generated by Django 3.1.7 on 2025-10-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('bike_model', models.CharField(max_length=50)),
                ('rental_days', models.CharField(max_length=50)),
                ('pickup_date', models.DateTimeField()),
                ('dropoff_date', models.DateTimeField()),
                ('rider_pic', models.ImageField(upload_to='riders/')),
                ('license_number', models.CharField(max_length=50)),
                ('aadhar_upload', models.FileField(upload_to='aadhar_docs/')),
                ('passport_upload', models.FileField(blank=True, null=True, upload_to='passport_docs/')),
                ('hotel_upload', models.FileField(blank=True, null=True, upload_to='hotel_docs/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('deposit_amount', models.PositiveIntegerField(default=0)),
                ('total_bill_amount', models.PositiveIntegerField(default=0)),
                ('advance_amount', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(default='none', max_length=50)),
                ('helmet_number_1', models.PositiveIntegerField(default=0)),
                ('helmet_number_2', models.PositiveIntegerField(default=0)),
                ('Name_of_staff', models.CharField(default='none', max_length=50)),
            ],
        ),
    ]
