# Generated by Django 3.1.7 on 2025-08-24 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('bike_model', models.CharField(max_length=50)),
                ('rental_days', models.PositiveIntegerField()),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('rider_pic', models.ImageField(upload_to='riders/')),
                ('license_number', models.CharField(max_length=50)),
                ('aadhar_upload', models.FileField(upload_to='aadhar_docs/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('deposit_amount', models.PositiveIntegerField(default=0)),
                ('total_bill_amount', models.PositiveIntegerField(default=0)),
                ('advance_amount', models.PositiveIntegerField(default=0)),
                ('remarks', models.PositiveIntegerField(default=0)),
                ('deposit_paymet_date', models.DateField(default=datetime.date(2025, 8, 24))),
            ],
        ),
    ]
