# Generated by Django 3.1.7 on 2025-10-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikerental',
            name='helmet_number_1',
        ),
        migrations.RemoveField(
            model_name='bikerental',
            name='helmet_number_2',
        ),
    ]
