# Generated by Django 3.1.7 on 2025-07-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerental',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
