# Generated by Django 3.1.7 on 2025-08-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0002_bikerental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerental',
            name='advance_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bikerental',
            name='deposit_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bikerental',
            name='remarks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bikerental',
            name='total_bill_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
