# Generated by Django 3.1.7 on 2025-09-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0003_auto_20250817_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerental',
            name='rental_days',
            field=models.CharField(max_length=50),
        ),
    ]
