# Generated by Django 5.2.5 on 2025-08-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0003_auto_20250817_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerental',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
