# Generated by Django 3.1.7 on 2025-09-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0004_auto_20250905_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerental',
            name='dropoff_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
    ]
