# Generated by Django 5.2.5 on 2025-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0004_alter_bikerental_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerental',
            name='return_due_date',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
