# Generated by Django 5.2.5 on 2025-08-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0005_bikerental_return_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerental',
            name='return_due_date',
            field=models.DateField(),
        ),
    ]
