# Generated by Django 5.2.5 on 2025-08-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0006_alter_bikerental_return_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikerental',
            name='return_due_date',
        ),
    ]
