# Generated by Django 5.2.5 on 2025-08-20 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosawaves_app', '0007_remove_bikerental_return_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerental',
            name='deposit_paymet_date',
            field=models.DateField(default=datetime.date(2025, 8, 20)),
        ),
    ]
